### ISSUE TITLE
thin.par

### ISSUE THREAD

**Issue by Tai-Rocha** [mlammens/spThin#17]
Dear Aiello-Lammens
Is there any criteria to set "Thinning parameter" function? Default is 10 kilometers. I mean, I should set this funtion using another software/package that give me this value (distance)?  Or choose any value and after I test my dataset for a spatial autocorrelation?

**Comment by mlammens** [comment]
Hi. Ideally you will base the thinning parameter on your knowledge (or someone else's) of the species biology - e.g., range size, daily dispersal distance, etc.. You could also do as you suggest, choose any value and check for spatial autocorrelation. But this may or may not correct the sampling bias problem. You can still have unequal sampling effort without spatial autocorrelation in your environmental variables. That said, this is still probably a good approach if you have know a priori knowledge of the species. Hope that helps.

**Comment by Tai-Rocha** [comment]
Thanks for your advice. 
Actually I read some papers to understand how authors used this function and one caught my attentiony because used by this way:    " ...using the 
spThin R package (Aiello-Lammens et al. 2015). This
distance was obtained through a SpThin automated
randomization approach that varies distances in order
to determine the best balance between bias removal and signal weakening (e.g. the distance that maximizes performance in spatially independent evaluations). ..."    So I thought the SpThin could provide me with the best distance for my dataset .

**Comment by mlammens** [comment]
Interesting. That's not a feature in spThin. The authors must have used spThin and some custom code to determine the best thinning distance for their dataset. You might consider asking the lead author on that paper about this. They may be willing to share code.
