### ISSUE TITLE
what input projection for spThin

### ISSUE THREAD

**Issue by rungec** [mlammens/spThin#31]
I'm running v0.2.0 of spThin, trying to thin a sf points dataframe of ~6000 points in GDA_2020_mgz56 (EPSG:7856) to 2km resolution. I'm using thin.par of 2000. The result should be approx 600 points but I'm coming up with 80 points and some are as close as 200m apart. Does spThin require data in a particular projection?

How does thin() work given the input can be a dataframe, and there is no crs parameter?

Here's my line of code
thin(loc.data=k_df, 
                      lat.col="lat", long.col="lon", spec.col="species", 
                      thin.par=2000, reps=20,
                      locs.thinned.list.return = TRUE,
                      write.files=FALSE, verbose=TRUE)

**Comment by rungec** [comment]
To answer my own question, I dug a bit deeper. spThin calculates distances using rdist.earth. This implements Haversine formula, which approximates linear distance from angular distance. 
So it should work for any lat lon coords in decimal degrees, but the accuracy will depend on the accuracy of the Haversine formula within your study zone.

**Comment by mlammens** [comment]
Thanks for reporting this @rungec . So is it the case that for your study region, the accuracy of the formula is low?
